active-services = "wireguard,scraping,dvpn,data_transfer"

[mmn]
  api-key = "dSdFFmZ8Xch9dgsEBD1H03at2I0USezQlXM5Xxuz"

[node]
  version = "1002229119"

[shaper]
  bandwidth = 125000.0
  enabled = false

[terms]
  consumer-agreed = true
  provider-agreed = true
  version = "0.0.53"
